### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by darkdarcool** [darkdarcool/ChitChat#1]
Hey @RayHanADev, I have a question that will help the dev of this.

Currently this is a class and you have to do this

``` javascript
e = require('chitchatsjs')
function l() {
  return 3
}
f = new e.TestCase('My Test', l())
f.toBeEqualToNum(3)
```
Or other ways. But what i can't figure out is how to do:

``` javascript
e.TestCase('MyTest', myFunc, () => {
   all of your tests
});
```

Is there a way to do that?

**Comment by RayhanADev** [comment]
@darkdarcool hii!!!

So do you want to run the function? Then do the following:
```js
function test(testName, testExec) {
// ... do whatever with testName, setup, etc.
  return testExec();
/* now call this.test(testName, testExec) in your class methods (i.e. toBeEqualToNum) 
    and it will return the result of the function passed in */
}
```

Does that make sense?

**Comment by darkdarcool** [comment]
Thanks so much! It works great! But lemme inv you to the repl because I have a couple complex questions to ask!

**Comment by darkdarcool** [comment]
Ray! I fixed it on my own when you left! Thanks for the help!

**Comment by RayhanADev** [comment]
@darkdarcool no problem! Sorry I had to jet for something important.

**Comment by darkdarcool** [comment]
No worries! I'll be posting it to npm later today and when the modules complete I'll post it to the repl talk!

**Comment by RayhanADev** [comment]
:D

**Comment by darkdarcool** [comment]
Maybe consider doing my tutorial and trying it? I would love to see wut you think! (I made sure to give you credit)

**Comment by darkdarcool** [comment]
If you don't wanna do that, here is my template:
https://replit.com/@darkdarcool/HandsomeWellgroomedTrial#tests/mytest.js

**Comment by IcingHackz** [comment]
unnamed repls are so funny
> "HandsomeWellgroomedTrial" xD

**Comment by darkdarcool** [comment]
Yas, do you like the module? I ~~need~~ would love your feedback!
