### ISSUE TITLE
wait a min...

### ISSUE THREAD

**Issue by iop3** [darkdarcool/ChitChat#4]
u said:
> # Credits
> * **My Brain**, for punching me in the stomach until I did this

are u literally talking about ur brain 🧠 or my repo ([My Brain](https://github.com/iop3/My-Brain-))

**Comment by darkdarcool** [comment]
MY brain

**Comment by darkdarcool** [comment]
I should make a repo of my big brain :)

**Comment by iop3** [comment]
lmfao ok
