### ISSUE TITLE
lol why

### ISSUE THREAD

**Issue by darkdarcool** [darkdarcool/ChitChat#5]
Hey @iop3, why the fork? Are you going to make a pull rqst.

**Comment by iop3** [comment]
oh i forked it? what? i didn't remember forking it. oh well, nah im not making a pr.

**Comment by darkdarcool** [comment]
ok

**Comment by iop3** [comment]
:)

**Comment by darkdarcool** [comment]
;)

**Comment by iop3** [comment]
;3

**Comment by iop3** [comment]
#7
