### ISSUE TITLE
ded link

### ISSUE THREAD

**Issue by iop3** [darkdarcool/ChitChat#7]
> ##### Pssst, if you wanna look at the source code, go [here](https://github.com/darkdarcool/chitchatjs)

https://github.com/darkdarcool/chitchatjs is a ded link...

**Comment by darkdarcool** [comment]
hmmmmmmmmm, ill fix it, I don't know why it is a dead like tho

**Comment by darkdarcool** [comment]
fixed!

**Comment by iop3** [comment]
:D

**Comment by iop3** [comment]
wait still ded

**Comment by darkdarcool** [comment]
hmm, not for me

**Comment by darkdarcool** [comment]
try again

**Comment by iop3** [comment]
nope.

**Comment by darkdarcool** [comment]
hmmm. It works for me. Can you gave me the link that you get when you click on the link?

**Comment by iop3** [comment]
ok um it is just the link i said in the issue but here it is again: https://github.com/darkdarcool/chitchatjs

**Comment by darkdarcool** [comment]
It's different for me. It changed the link on my end. I think it's something wrong on your end. I changed it and it's working for me

**Comment by iop3** [comment]
hmm...did u commit the change?

**Comment by iop3** [comment]
im positive that there's nothing wrong on my end...

**Comment by iop3** [comment]
let's ask someone else. @JBYT27 <-- yes i purposely pinged u. is the link in the readme.md ded or is it working?

**Comment by darkdarcool** [comment]
Yea I committed the change

**Comment by iop3** [comment]
hmmmm

**Comment by iop3** [comment]
i dunno then...

**Comment by darkdarcool** [comment]
:/

**Comment by iop3** [comment]
:\

**Comment by JBYT27** [comment]
I have been pung.

And the link has been buried in a grave.

**Comment by iop3** [comment]
told u @darkdarcool. it's not me, other people have trouble too. so it's ur problem @darkdarcool >:(

**Comment by darkdarcool** [comment]
It works on my phone, and on my laptop, and I checked on editing, it works, can you give me the link for the main webpage of this repo so I can put it in?

There's not much I can do

**Comment by iop3** [comment]
what do you mean by "main webpage of this repo"?

**Comment by darkdarcool** [comment]
Like, the link you see when your in the webpage of this repo

**Comment by iop3** [comment]
https://github.com/darkdarcool/ChitChat

**Comment by darkdarcool** [comment]
![image](https://user-images.githubusercontent.com/66882633/119242971-7cf4ec00-bb17-11eb-91de-a7bc2602bbed.png)
This is me updating it.

**Comment by iop3** [comment]
hold up...that's replit! Not github lol

**Comment by darkdarcool** [comment]
IK, this is prof that I'm updating the link in the post

**Comment by iop3** [comment]
how about github?

**Comment by iop3** [comment]
did u change it on github?

**Comment by darkdarcool** [comment]
wdym

**Comment by darkdarcool** [comment]
I think I fixed

**Comment by iop3** [comment]
yes u did :)

**Comment by darkdarcool** [comment]
Noice
